pipelines:
  - name: docker_build_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: docker_afgroup             # Execute build and push on the same node
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: jfrog.local:5000/ubi7
          dockerImageTag: $run_number
          inputResources:
            - name: repo_docker_build_push
          integrations:
            - name: demoArt

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: docker_afgroup             # Execute build and push on the same node
          targetRepository: docker-local
          integrations:
            - name: demoArt
          inputSteps:
            - name: docker_build

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_docker_build_push