pipelines:
  - name: docker_build_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: docker_afgroup             # Execute build and push on the same node
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: anchore.jfrog.io/anchore-docker/ubi7/ubi
          dockerImageTag: 7.7
          inputResources:
            - name: repo_docker_build_push